services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-1}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ls
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601" 
    environment:
      OPENSEARCH_HOSTS: "http://secure-devpillow-study.us-east-1.opensearch.localhost.localstack.cloud:4566"
      OPENSEARCH_USERNAME: "admin"
      OPENSEARCH_PASSWORD: "devpillowsecurepassword"
    networks:
      - ls
    dns:
      - "172.22.0.2"
    depends_on:
      - localstack
networks:
  ls: